# HTTP Server
server:
  port: 8081
spring:
  cloud:
   config:
    server:
      git:
       default-label: multiple-instances 
       uri: https://github.com/jcotrado/ms-springboot-basico-configService
       search-paths: config-data
  application:
    name: config-service  
 