server:
  port: 8081
spring:
  cloud:
   config:
    server:
      git:
       default-label: config-server #branch en repositorio github
       uri: https://github.com/jcotrado/ms-springboot-basico-usuario.git 
       search-paths : config-data
  application:
    name: config-service  
 