server:
  port: 8000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable:true
      routes:
        - id: usuario-service
          uri: lba://user-service
          predicates:
            - Path=/user/**
        - id: carro-service
          uri: lba://carro-service
          predicates:
            - Path=/carro/**
        - id: moto-service
          uri: lba://moto-service
          predicates:
            - Path=/moto/**     